name: PR Check

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight

jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - name: Print branch name
        run: echo "PR check running for branch:${{ github.head_ref }}"
